on:
    push:
        branches:
            - master
            - main
    pull_request:
name: Security
jobs:
  Gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3.2.0
      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: ./...
