on:
    push:
        branches:
            - master
            - main
    pull_request:
name: Tests
jobs:
    Tests:
        name: Tests
        strategy:
            matrix:
                go-version:
                    - 1.18.x
                    - 1.20.x
                    - 1.21.x
                platform:
                    - ubuntu-latest
                    - windows-latest
        runs-on: '${{ matrix.platform }}'
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Run Test
                run: go test ./... -v -race
